name: pp1solver
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - absl-py=0.9.0=py37_0
  - astor=0.8.0=py37_0
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_0
  - cycler=0.10.0=py37_0
  - freetype=2.9.1=ha9979f8_1
  - gast=0.2.2=py37_0
  - google-pasta=0.1.8=py_0
  - grpcio=1.16.1=py37h351948d_1
  - h5py=2.10.0=py37h5e291fa_0
  - hdf5=1.10.4=h7ebc959_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha66f8fd_1
  - intel-openmp=2020.0=166
  - jpeg=9b=hb83a4c4_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py37ha925a31_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.11.3=h7bd577a_0
  - markdown=3.1.1=py37_0
  - matplotlib=3.1.3=py37_0
  - matplotlib-base=3.1.3=py37h64f37c6_0
  - mkl=2020.0=166
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.0.15=py37h14836fe_0
  - mkl_random=1.1.0=py37h675688f_0
  - numpy=1.18.1=py37h93ca92e_0
  - numpy-base=1.18.1=py37hc3f5095_1
  - openssl=1.1.1d=he774522_4
  - opt_einsum=3.1.0=py_0
  - pip=20.0.2=py37_1
  - protobuf=3.11.3=py37h33f27b4_0
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyreadline=2.1=py37_1
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - scipy=1.4.1=py37h9439919_0
  - setuptools=45.2.0=py37_0
  - sip=4.19.8=py37h6538335_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=he774522_0
  - tensorboard=2.0.0=pyhb38c66f_1
  - tensorflow=2.0.0=eigen_py37hbfc5123_0
  - tensorflow-base=2.0.0=eigen_py37h01553b8_0
  - tensorflow-estimator=2.0.0=pyh2649769_0
  - termcolor=1.1.0=py37_1
  - tornado=6.0.3=py37he774522_3
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - wrapt=1.11.2=py37he774522_0
  - zlib=1.2.11=h62dcd97_3
prefix: C:\Users\jmu\AppData\Local\Continuum\anaconda3\envs\pp1solver

